const initialState = {
  properties: [
    {
      id: 1,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 2,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 3,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 4,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 5,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 6,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 7,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 8,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 9,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 10,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 11,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
    {
      id: 12,
      img: '',
      address: '2151 Mulberry Avenue',
      city: '63 Birch Street',
      price: '$25.000',
      bathrooms: 1,
      bedrooms: 2,
      area: '165m2',
      garages: 1,
      features: {
        airConditioning: true,
        cableTv: true,
        fireplace: true,
        sauna: true,
        balcony: true,
        dishwasher: true,
        grill: true,
        landscaping: true,
        badding: true,
        familyRoom: true,
        outdoorKitchen: true,
      },
    },
  ],
};

export default initialState;
